# Usage:
# docker system prune -a
# docker rmi $(docker images -f "dangling=true" -q)
# docker volume rm $(docker volume ls -qf dangling=true)
# docker restart $(docker ps -f health=unhealthy)
# docker stop $(docker ps -aq) && docker rm $(docker ps -aq)
# docker exec -it mob_AndroidApp_1 tail -f /var/log/supervisor/docker-android.stdout.log
# COMPOSE_HTTP_TIMEOUT=200 docker-compose up --scale AndroidApp=8 --scale MobileSite=0 --remove-orphans  -d
version: '2.2'

services:
  autoheal:
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=240   # check every 5 seconds
      - AUTOHEAL_START_PERIOD=300   # wait 0 second before first health check
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=180   # Docker waits max 10 seconds (the Docker default) for a container to stop before killing during restarts (container overridable via label, see below)
      - DOCKER_SOCK=/var/run/docker.sock   # Unix socket for curl requests to Docker API
      - CURL_TIMEOUT=15     # --max-time seconds for curl requests to Docker API
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  selenium_hub:
    image: selenium/hub
    container_name: selenium_hub
    hostname: selenium_hub
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "bash", "/opt/bin/check-grid.sh"]
      interval: 15s
      timeout: 30s
      retries: 5
    environment:
      - GRID_MAX_SESSION=25
      - TZ=Asia/Tehran
      # In seconds, maps to "browserTimeout"
      - GRID_BROWSER_TIMEOUT=60
      # In seconds, maps to "timeout"
      - GRID_TIMEOUT=120
      # In milliseconds, maps to "newSessionWaitTimeout"
      - GRID_NEW_SESSION_WAIT_TIMEOUT=-1

  AndroidApp:
    image: mehr1353/docker-android-x86-8.1
    # image: budtmo/docker-android-x86-10.0
    privileged: true
    # Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
    volumes:
      # - /var/lib/docker/qa/vids/AndroidApp:/tmp/video
      # - /dev/kvm:/dev/kvm
      # - ./media:/media
      - ./src/utils.sh:/root/src/utils.sh
      # - ./src/app.py:/root/src/app.py
      - ./devices:/root/devices
      # - ./src/record.sh:/root/src/record.sh
      # - ./src/google_play_services.apk:/root/src/google_play_services.apk
      # - ./src/google_play_store.apk:/root/src/google_play_store.apk
      # - ./src/google_chrome.apk:/root/src/google_chrome.apk
      # - ./chromedriver:/root/chromedriver

    depends_on:
      - selenium_hub
    ports:
      - 6080
    environment:
      - DEVICE=samsung galaxy s6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - SELENIUM_PORT=4444
      - AUTO_RECORD=true
      - RELAXED_SECURITY=true
      - TZ=Asia/Tehran
    labels:
      - "autoheal=true"

  MobileSite:
    image: mehr1353/docker-android-x86-8.1
    # image: budtmo/docker-android-x86-10.0
    privileged: true
    scale: 0
    depends_on:
      - selenium_hub
    ports:
      - 6080
    volumes:
      # - /var/lib/docker/qa/vids/MobileSite:/tmp/video
      # - /dev/kvm:/dev/kvm
      # - ./media:/media
      - ./src/utils.sh:/root/src/utils.sh
      # - ./src/app.py:/root/src/app.py
      - ./devices:/root/devices
      # - ./src/record.sh:/root/src/record.sh
      # - ./src/google_play_services.apk:/root/src/google_play_services.apk
      # - ./src/google_play_store.apk:/root/src/google_play_store.apk
      # - ./src/google_chrome.apk:/root/src/google_chrome.apk
      # - ./chromedriver:/root/chromedriver
    environment:
      - DEVICE=samsung galaxy s6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - SELENIUM_PORT=4444
      - MOBILE_WEB_TEST=true
      - AUTO_RECORD=true
      - RELAXED_SECURITY=true
      - TZ=Asia/Tehran
      - SE_OPTS=-browserTimeout 100 -timeout 100
    labels:
      - "autoheal=true"
