# Usage:
# docker system prune -a
# docker rmi $(docker images -f "dangling=true" -q)
# docker volume rm $(docker volume ls -qf dangling=true)
# docker restart $(docker ps -f health=unhealthy)
# docker stop $(docker ps -aq) && docker rm $(docker ps -aq)
# sudo docker ps -a | grep Exit | cut -d ' ' -f 1 | xargs sudo docker rm
# docker exec -it mob_AndroidApp_1 tail -f /var/log/supervisor/docker-android.stdout.log
# COMPOSE_HTTP_TIMEOUT=200 docker-compose up --scale AndroidApp=8 --scale MobileSite=0 --remove-orphans  -d
version: '2.2'

services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal_mob
    hostname: autoheal_mob
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=10   # check every 5 seconds
      - AUTOHEAL_START_PERIOD=180   # wait 0 second before first health check
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30   # Docker waits max 10 seconds (the Docker default) for a container to stop before killing during restarts (container overridable via label, see below)
      - DOCKER_SOCK=/var/run/docker.sock   # Unix socket for curl requests to Docker API
      - CURL_TIMEOUT=10     # --max-time seconds for curl requests to Docker API
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  selenium_mob_hub:
    image: selenium/hub
    container_name: selenium_mob_hub
    hostname: selenium_mob_hub
    ports:
      - "6677:4444"
    healthcheck:
      test: ["CMD", "bash", "/opt/bin/check-grid.sh"]
      interval: 15s
      timeout: 30s
      retries: 5
    environment:
      - GRID_MAX_SESSION=10
      - TZ=Asia/Tehran
      # In seconds, maps to "browserTimeout"
      - GRID_BROWSER_TIMEOUT=60
      # In seconds, maps to "timeout"
      - GRID_TIMEOUT=120
      # In milliseconds, maps to "newSessionWaitTimeout"
      - GRID_NEW_SESSION_WAIT_TIMEOUT=-1

  MobileSite:
    image: mehr1353/docker-android-x86-8.1:ga1.0
    # image: budtmo/docker-android-x86-10.0
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    scale: 5
    depends_on:
      - selenium_mob_hub
    ports:
      - 6080
    # cpus: "1"
    mem_limit: "4096m"
    volumes:
      # - /var/lib/docker/qa/vids/MobileSite:/tmp/video
      - /home/qa/web/videos/MobileSite:/tmp/video
      # - ./media:/media
      # - ./src/utils.sh:/root/src/utils.sh
      # - ./src/app.py:/root/src/app.py
      # - ../devices:/root/devices
      # - ./src/record.sh:/root/src/record.sh
      # - ./src/google_play_services.apk:/root/src/google_play_services.apk
      # - ./src/google_play_store.apk:/root/src/google_play_store.apk
      # - ./src/google_chrome.apk:/root/src/google_chrome.apk
      # - ./chromedriver:/root/chromedriver
    environment:
      - DEVICE=Samsung Galaxy S10 E
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_mob_hub
      - SELENIUM_PORT=4444
      - MOBILE_WEB_TEST=true
      - AUTO_RECORD=true
      - RELAXED_SECURITY=true
      - TZ=Asia/Tehran
      - SE_OPTS=-browserTimeout 100 -timeout 100
      - QEMU_AUDIO_DRV=none
      - EMULATOR_ARGS=-no-snapshot-save -memory 2048 -no-boot-anim -noaudio -no-audio -qemu -m 2048
    labels:
      - "autoheal=true"
